use std::{
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use rust_skgen::{
    domain::{
        ContentFormat, DiscoveryConfiguration, DiscoveryScope, SiteBoundary, SourceUrl,
        TraversalMode,
    },
    metadata::{ManagedSkillMetadata, content_digest},
    storage::{METADATA_FILE_NAME, ManagedSkillStatus, SkillLocator},
};

struct TemporarySkillsDirectory {
    path: PathBuf,
}

impl TemporarySkillsDirectory {
    fn new() -> Self {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!("rust-skgen-discovery-{unique}"));
        fs::create_dir(&path).unwrap();
        Self { path }
    }

    fn create_skill(&self, name: &str) -> PathBuf {
        let path = self.path.join(name);
        fs::create_dir(&path).unwrap();
        path
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TemporarySkillsDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn valid_metadata() -> ManagedSkillMetadata {
    let source_url = SourceUrl::parse("https://docs.example.com/guide").unwrap();
    let discovery = DiscoveryConfiguration::new(
        DiscoveryScope::SameSite,
        Some(SiteBoundary::ExactHost),
        Vec::new(),
        TraversalMode::All,
        None,
        ContentFormat::GuideWithReferences,
        false,
    )
    .unwrap();

    ManagedSkillMetadata::new(source_url, discovery, content_digest("# Generated skill\n"))
}

#[test]
fn locates_only_skills_with_valid_generator_metadata_as_managed() {
    let skills = TemporarySkillsDirectory::new();
    let managed = skills.create_skill("managed-skill");
    let unmanaged = skills.create_skill("unmanaged-skill");
    fs::write(
        managed.join(METADATA_FILE_NAME),
        valid_metadata().to_json().unwrap(),
    )
    .unwrap();
    fs::write(unmanaged.join("notes.txt"), "Not generated by rust-skgen.").unwrap();

    let located = SkillLocator::new(skills.path()).locate().unwrap();

    assert_eq!(located.len(), 2);
    assert_eq!(located[0].name().as_str(), "managed-skill");
    assert!(matches!(
        located[0].status(),
        ManagedSkillStatus::Managed(_)
    ));
    assert_eq!(located[1].name().as_str(), "unmanaged-skill");
    assert!(matches!(
        located[1].status(),
        ManagedSkillStatus::MetadataMissing
    ));
}

#[test]
fn reports_missing_and_invalid_metadata_without_treating_them_as_managed() {
    let skills = TemporarySkillsDirectory::new();
    let missing = skills.create_skill("missing-metadata");
    let invalid = skills.create_skill("invalid-metadata");
    fs::write(invalid.join(METADATA_FILE_NAME), "not JSON").unwrap();
    fs::write(missing.join("SKILL.md"), "# User maintained skill\n").unwrap();

    let located = SkillLocator::new(skills.path()).locate().unwrap();

    assert_eq!(located[0].name().as_str(), "invalid-metadata");
    assert!(matches!(
        located[0].status(),
        ManagedSkillStatus::InvalidMetadata(_)
    ));
    assert_eq!(located[1].name().as_str(), "missing-metadata");
    assert!(matches!(
        located[1].status(),
        ManagedSkillStatus::MetadataMissing
    ));
    assert!(located.iter().all(|skill| !skill.is_managed()));
}

#[test]
fn does_not_treat_metadata_from_a_different_generator_as_managed() {
    let skills = TemporarySkillsDirectory::new();
    let foreign = skills.create_skill("foreign-skill");
    let metadata = valid_metadata().to_json().unwrap().replace(
        "\"generator\":\"rust-skgen\"",
        "\"generator\":\"other-generator\"",
    );
    fs::write(foreign.join(METADATA_FILE_NAME), metadata).unwrap();

    let located = SkillLocator::new(skills.path()).locate().unwrap();

    assert_eq!(located.len(), 1);
    assert!(matches!(
        located[0].status(),
        ManagedSkillStatus::InvalidMetadata(_)
    ));
    assert!(!located[0].is_managed());
}
